export const specListData = [
  {
    type: '通用计算型s6',
    name: 's6.small.1',
    disabled: false,
    selected: false,
    vcpus: '1vCPUs',
    memory: '1GiB',
    cpu: 'Intel Cascade Lake 2.6GHz',
    pos: '0.1 / 0.8 Gbit/s',
    pps: '10万PPS',
    ipv6: '是',
    price: '¥32.20/月',
  },
  {
    type: '通用计算型s6',
    name: 's6.medium.2',
    disabled: false,
    selected: false,
    vcpus: '1vCPUs',
    memory: '2GiB',
    cpu: 'Intel Cascade Lake 2.6GHz',
    pos: '0.1 / 0.8 Gbit/s',
    pps: '10万PPS',
    ipv6: '是',
    price: '¥72.20/月',
  },
  {
    type: '通用计算型s6',
    name: 's6.medium.4',
    disabled: false,
    selected: false,
    vcpus: '1vCPUs',
    memory: '4GiB',
    cpu: 'Intel Cascade Lake 2.6GHz',
    pos: '0.1 / 0.8 Gbit/s',
    pps: '10万PPS',
    ipv6: '是',
    price: '¥107.08/月',
  },
  {
    type: '通用计算型s6',
    name: 's6.large.2',
    disabled: false,
    selected: false,
    vcpus: '2vCPUs',
    memory: '4GiB',
    cpu: 'Intel Cascade Lake 2.6GHz',
    pos: '0.2 / 0.15 Gbit/s',
    pps: '15万PPS',
    ipv6: '是',
    price: '¥152.30/月',
  },
  {
    type: '通用计算型s6',
    name: 's6.large.4',
    disabled: false,
    selected: false,
    vcpus: '2vCPUs',
    memory: '8GiB',
    cpu: 'Intel Cascade Lake 2.6GHz',
    pos: '0.2 / 0.15 Gbit/s',
    pps: '15万PPS',
    ipv6: '是',
    price: '¥215.60/月',
  },
  {
    type: '通用计算型s6',
    name: 's6.xlarge.2',
    disabled: false,
    selected: false,
    vcpus: '4vCPUs',
    memory: '8GiB',
    cpu: 'Intel Cascade Lake 2.6GHz',
    pos: '0.35 / 2 Gbit/s',
    pps: '25万PPS',
    ipv6: '是',
    price: '¥304.30/月',
  },
  {
    type: '通用计算型s6',
    name: 's6.xlarge.4',
    disabled: false,
    selected: false,
    vcpus: '4vCPUs',
    memory: '16GiB',
    cpu: 'Intel Cascade Lake 2.6GHz',
    pos: '0.35 / 2 Gbit/s',
    pps: '25万PPS',
    ipv6: '是',
    price: '¥431.20/月',
  },
  {
    type: '通用计算型s6',
    name: 's6.2xlarge.2',
    disabled: false,
    selected: false,
    vcpus: '8vCPUs',
    memory: '16GiB',
    cpu: 'Intel Cascade Lake 2.6GHz',
    pos: '0.75 / 3 Gbit/s',
    pps: '50万PPS',
    ipv6: '是',
    price: '¥608.60/月',
  },
  {
    type: '通用计算型s6',
    name: 's6.2xlarge.4',
    disabled: false,
    selected: false,
    vcpus: '8vCPUs',
    memory: '32GiB',
    cpu: 'Intel Cascade Lake 2.6GHz',
    pos: '0.75 / 3 Gbit/s',
    pps: '50万PPS',
    ipv6: '是',
    price: '¥862.40/月',
  },
]
